/**
 * CANONICAL TAG IMPLEMENTATION REFERENCE
 * How canonical tags are generated and managed throughout the site
 * Date: December 17, 2025
 */

// ============================================================================
// HOW CANONICAL TAGS ARE IMPLEMENTED
// ============================================================================

/**
 * LOCATION: src/lib/seo.js - useSEO() hook
 * 
 * The useSEO hook automatically generates canonical tags for all pages.
 * 
 * Example from implementation:
 * 
 * export function useSEO({ title, description, image, noIndex = false, canonical } = {}) {
 *   useEffect(() => {
 *     const url = canonical || (typeof window !== 'undefined' 
 *       ? window.location.href.split('#')[0]  // Strips fragment identifiers
 *       : undefined);
 * 
 *     if (url) {
 *       updateLink('canonical', url);  // Creates/updates <link rel="canonical">
 *     }
 *   }, [title, description, image, noIndex, canonical]);
 * }
 * 
 * BEHAVIOR:
 * 1. If no canonical is provided, it uses window.location.href
 * 2. Strips fragment identifiers (#) to prevent duplicate canonicals
 * 3. Automatically creates or updates <link rel="canonical"> in <head>
 * 4. Runs on every page render/route change
 */

export const canonicalImplementation = {
  mechanism: 'Auto-generated from window.location.href on every page',
  defaultBehavior: 'Uses current URL as canonical',
  fragmentHandling: 'Strips # to prevent duplicate canonicals',
  overrideOption: 'Can pass explicit canonical parameter if needed',
  updateTiming: 'Runs via useEffect dependency array',
};

// ============================================================================
// CANONICAL TAG EXAMPLES BY PAGE
// ============================================================================

export const canonicalExamples = {
  homepage: {
    path: '/',
    generatedCanonical: 'https://fortis-secured.vercel.app/',
    implementation: 'Auto-generated by useSEO()',
    usage: 'useSEO({ title: "...", description: "..." })',
    htmlOutput: '<link rel="canonical" href="https://fortis-secured.vercel.app/">',
  },
  
  servicesHub: {
    path: '/services',
    generatedCanonical: 'https://fortis-secured.vercel.app/services',
    implementation: 'Auto-generated by useSEO()',
    usage: 'useSEO({ title: "...", description: "..." })',
    htmlOutput: '<link rel="canonical" href="https://fortis-secured.vercel.app/services">',
  },
  
  mannedGuardingService: {
    path: '/services/manned-guarding',
    generatedCanonical: 'https://fortis-secured.vercel.app/services/manned-guarding',
    implementation: 'Auto-generated by useSEO()',
    usage: 'useSEO({ title: "...", description: "...", image: getServiceOGImage(...) })',
    htmlOutput: '<link rel="canonical" href="https://fortis-secured.vercel.app/services/manned-guarding">',
    fileLocation: 'src/pages/services/MannedGuarding.jsx',
  },
  
  doorSupervisionService: {
    path: '/services/door-supervision',
    generatedCanonical: 'https://fortis-secured.vercel.app/services/door-supervision',
    implementation: 'Auto-generated by useSEO()',
    usage: 'useSEO({ title: "...", description: "...", image: getServiceOGImage(...) })',
    htmlOutput: '<link rel="canonical" href="https://fortis-secured.vercel.app/services/door-supervision">',
    fileLocation: 'src/pages/services/DoorSupervision.jsx',
  },
  
  eventSecurityService: {
    path: '/services/event-security',
    generatedCanonical: 'https://fortis-secured.vercel.app/services/event-security',
    implementation: 'Auto-generated by useSEO()',
    usage: 'useSEO({ title: "...", description: "...", image: getServiceOGImage(...) })',
    htmlOutput: '<link rel="canonical" href="https://fortis-secured.vercel.app/services/event-security">',
    fileLocation: 'src/pages/services/EventSecurity.jsx',
  },
  
  corporateSecurityService: {
    path: '/services/corporate-security',
    generatedCanonical: 'https://fortis-secured.vercel.app/services/corporate-security',
    implementation: 'Auto-generated by useSEO()',
    usage: 'useSEO({ title: "...", description: "...", image: getServiceOGImage(...) })',
    htmlOutput: '<link rel="canonical" href="https://fortis-secured.vercel.app/services/corporate-security">',
    fileLocation: 'src/pages/services/CorporateSecurity.jsx',
  },
  
  constructionSecurityService: {
    path: '/services/construction-site-security',
    generatedCanonical: 'https://fortis-secured.vercel.app/services/construction-site-security',
    implementation: 'Auto-generated by useSEO()',
    usage: 'useSEO({ title: "...", description: "...", image: getServiceOGImage(...) })',
    htmlOutput: '<link rel="canonical" href="https://fortis-secured.veravel.app/services/construction-site-security">',
    fileLocation: 'src/pages/services/ConstructionSiteSecurity.jsx',
  },
  
  about: {
    path: '/about',
    generatedCanonical: 'https://fortis-secured.veravel.app/about',
    implementation: 'Auto-generated by useSEO()',
    usage: 'useSEO({ title: "...", description: "...", image: getDefaultOGImage() })',
    htmlOutput: '<link rel="canonical" href="https://fortis-secured.veravel.app/about">',
    fileLocation: 'src/pages/About.jsx',
  },
  
  contact: {
    path: '/contact',
    generatedCanonical: 'https://fortis-secured.veravel.app/contact',
    implementation: 'Auto-generated by useSEO()',
    usage: 'useSEO({ title: "...", description: "...", image: getDefaultOGImage() })',
    htmlOutput: '<link rel="canonical" href="https://fortis-secured.veravel.app/contact">',
    fileLocation: 'src/pages/Contact.jsx',
  },
  
  joinTheTeam: {
    path: '/join-the-team',
    generatedCanonical: 'https://fortis-secured.veravel.app/join-the-team',
    implementation: 'Auto-generated by useSEO()',
    usage: 'useSEO({ title: "...", description: "...", image: getDefaultOGImage() })',
    htmlOutput: '<link rel="canonical" href="https://fortis-secured.veravel.app/join-the-team">',
    fileLocation: 'src/pages/JoinTheTeam.jsx',
  },
  
  privacyPolicy: {
    path: '/privacy-policy',
    generatedCanonical: 'https://fortis-secured.veravel.app/privacy-policy',
    implementation: 'Auto-generated by useSEO()',
    usage: 'useSEO({ title: "...", description: "...", image: getDefaultOGImage(), noIndex: false })',
    htmlOutput: '<link rel="canonical" href="https://fortis-secured.veravel.app/privacy-policy">',
    fileLocation: 'src/pages/PrivacyPolicy.jsx',
  },
  
  terms: {
    path: '/terms',
    generatedCanonical: 'https://fortis-secured.veravel.app/terms',
    implementation: 'Auto-generated by useSEO()',
    usage: 'useSEO({ title: "...", description: "...", image: getDefaultOGImage(), noIndex: false })',
    htmlOutput: '<link rel="canonical" href="https://fortis-secured.veravel.app/terms">',
    fileLocation: 'src/pages/Terms.jsx',
  },
  
  cookiePolicy: {
    path: '/cookie-policy',
    generatedCanonical: 'https://fortis-secured.veravel.app/cookie-policy',
    implementation: 'Auto-generated by useSEO()',
    usage: 'useSEO({ title: "...", description: "...", image: getDefaultOGImage(), noIndex: false })',
    htmlOutput: '<link rel="canonical" href="https://fortis-secured.veravel.app/cookie-policy">',
    fileLocation: 'src/pages/CookiePolicy.jsx',
  },
};

// ============================================================================
// PORTAL PAGES - NOINDEX HANDLING
// ============================================================================

export const portalPagesHandling = {
  noindexStrategy: 'All portal pages explicitly noindex to prevent indexing',
  
  portalRoutes: [
    '/portal',
    '/portal/clients',
    '/portal/sites',
    '/portal/guards',
    '/portal/scheduling',
    '/portal/tasks',
    '/portal/incidents',
    '/portal/assets',
    '/portal/messages',
    '/portal/finance',
    '/portal/reports',
    '/portal/settings',
    // ... and others
  ],
  
  implementation: {
    location: 'src/layouts/PortalLayout.jsx',
    mechanism: 'useSEO({ noIndex: true }) on portal wrapper',
    effect: 'Sets meta[name="robots"] = "noindex, nofollow"',
    rationale: 'Portal requires authentication; should not be publicly indexed',
  },
  
  htmlOutput: '<meta name="robots" content="noindex, nofollow">',
  
  verification: 'Google Search Console will not index portal pages',
};

// ============================================================================
// URL STRUCTURE BREAKDOWN
// ============================================================================

export const urlStructureBreakdown = {
  patterns: {
    singleLevel: {
      pattern: '/{slug}',
      examples: ['/', '/about', '/contact', '/join-the-team'],
      usage: 'Main pages and top-level sections',
    },
    
    twoLevel: {
      pattern: '/{category}/{item}',
      examples: ['/services/manned-guarding', '/services/event-security'],
      usage: 'Services and categorized content',
    },
    
    parameterized: {
      pattern: '/{category}/{id}',
      examples: ['/portal/clients/123', '/portal/sites/456'],
      usage: 'Dynamic routes with IDs (portal)',
    },
  },
  
  conventions: {
    case: 'Lowercase only (no UPPERCASE or MixedCase)',
    separator: 'Hyphen (-) for word separation',
    keywords: 'Descriptive, SEO-friendly terms',
    length: 'Short and memorable when possible',
    hierarchy: 'Logical parent-child relationships',
  },
  
  keywords: {
    root: 'fortis-secured.veravel.app (brand)',
    services: '/services (primary keyword)',
    serviceDetail: 'manned-guarding, door-supervision, event-security, corporate-security, construction-site-security',
    legal: 'privacy-policy, terms, cookie-policy',
    engagement: 'about, contact, join-the-team',
  },
};

// ============================================================================
// SEO BENEFITS OF CANONICAL TAGS
// ============================================================================

export const seoBenefits = {
  rankingSignalConsolidation: {
    benefit: 'All ranking signals flow to single canonical URL',
    impact: 'Prevents ranking power from being split across duplicates',
    outcome: 'Higher ranking potential for primary URL',
  },
  
  duplicateContentAvoidance: {
    benefit: 'Tells Google which version to prioritize',
    impact: 'Prevents duplicate content penalties',
    outcome: 'Clean, efficient index without duplicates',
  },
  
  crawlEfficiency: {
    benefit: 'Googlebot focuses on canonical version only',
    impact: 'Saves crawl budget for new content',
    outcome: 'Faster indexing of new pages',
  },
  
  urlVariationHandling: {
    benefit: 'Handles session IDs, parameters, trailing slashes',
    impact: 'Single version indexed regardless of URL variations',
    outcome: 'Unified ranking and traffic metrics',
  },
  
  trustAndAuthority: {
    benefit: 'Consolidates backlinks to single URL',
    impact: 'Stronger authority signals for that URL',
    outcome: 'Better rankings for competitive keywords',
  },
};

// ============================================================================
// VERIFICATION METHODS
// ============================================================================

export const verificationMethods = {
  googleSearchConsole: {
    tool: 'Google Search Console',
    steps: [
      '1. Add property (fortis-secured.veravel.app)',
      '2. Go to Coverage report',
      '3. Check "Excluded" section for duplicate content',
      '4. Use URL Inspection tool for individual pages',
      '5. Verify canonical shown matches expected',
    ],
    expectedResult: 'Canonical matches the page URL',
  },
  
  devTools: {
    tool: 'Chrome DevTools',
    steps: [
      '1. Right-click page → Inspect',
      '2. Go to Elements tab',
      '3. Scroll to <head> section',
      '4. Find <link rel="canonical">',
      '5. Verify href attribute',
    ],
    htmlFormat: '<link rel="canonical" href="https://fortis-secured.veravel.app/page">',
  },
  
  pageSource: {
    tool: 'View Page Source',
    steps: [
      '1. Visit page in browser',
      '2. Right-click → View Page Source (or Ctrl+U)',
      '3. Search for "canonical" (Ctrl+F)',
      '4. Verify <link rel="canonical"> present',
    ],
  },
  
  curl: {
    tool: 'Command Line (curl)',
    command: 'curl -s https://fortis-secured.veravel.app/services/manned-guarding | grep canonical',
    expectedOutput: '<link rel="canonical" href="https://fortis-secured.veravel.app/services/manned-guarding">',
  },
  
  seoTools: {
    tools: ['Moz', 'Ahrefs', 'SEMrush', 'Screaming Frog'],
    what: 'Crawl site and report canonical tags',
    value: 'Verify consistency across all pages',
  },
};

// ============================================================================
// TROUBLESHOOTING GUIDE
// ============================================================================

export const troubleshooting = {
  missingCanonical: {
    issue: 'Canonical tag not appearing in source code',
    cause: 'useSEO() not called or not imported',
    solution: 'Ensure every page component calls useSEO() at top level',
  },
  
  wrongCanonical: {
    issue: 'Canonical points to wrong URL',
    cause: 'Browser URL incorrect or manual canonical override',
    solution: 'Check page route in App.jsx; verify canonical parameter not passed',
  },
  
  duplicateCanonicals: {
    issue: 'Multiple <link rel="canonical"> tags on one page',
    cause: 'Multiple useSEO() calls or manual link insertion',
    solution: 'Ensure only one useSEO() call per component',
  },
  
  httpVsHttps: {
    issue: 'Canonical uses http instead of https',
    cause: 'Development environment difference',
    solution: 'Canonicals always use https on production (Vercel enforces)',
  },
  
  www: {
    issue: 'Canonical includes www or excludes www inconsistently',
    cause: 'Domain routing variation',
    solution: 'Fortis uses non-www (fortis-secured.veravel.app)',
  },
};

// ============================================================================
// MONITORING & MAINTENANCE
// ============================================================================

export const monitoring = {
  googleSearchConsole: [
    'Monitor Coverage report for duplicate content warnings',
    'Check URL Inspection tool for canonical consistency',
    'Watch for "Excluded" URLs due to canonical',
  ],
  
  analytics: [
    'Verify traffic consolidating to canonical URLs',
    'Check referrer data shows canonical URLs',
    'Monitor conversion paths use canonical URLs',
  ],
  
  ranking: [
    'Track keyword rankings for each canonical',
    'Monitor CTR from search results',
    'Watch for rank fluctuations post-update',
  ],
  
  crawling: [
    'Monitor crawl errors in Search Console',
    'Watch redirect chains (should be minimal)',
    'Check Googlebot activity and crawl efficiency',
  ],
};

export default {
  canonicalImplementation,
  canonicalExamples,
  portalPagesHandling,
  urlStructureBreakdown,
  seoBenefits,
  verificationMethods,
  troubleshooting,
  monitoring,
};
