const AUTHENTICATED_RW = [
  'read("users")',
  'create("users")',
  'update("users")',
  'delete("users")',
];

export const COLLECTION_DEFINITIONS = [
  {
    collectionId: 'users',
    name: 'Users',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'externalId', type: 'string', size: 255, required: true },
      { key: 'email', type: 'string', size: 320, required: true },
      { key: 'phone', type: 'string', size: 32, required: false },
      {
        key: 'role',
        type: 'enum',
        elements: ['admin', 'manager', 'staff', 'client'],
        required: true,
        default: 'staff',
      },
      {
        key: 'status',
        type: 'enum',
        elements: ['active', 'suspended', 'compliance_blocked', 'archived'],
        required: true,
        default: 'active',
      },
      { key: 'metadata', type: 'json', required: false, size: 8192 },
      { key: 'lastLoginAt', type: 'datetime', required: false },
      { key: 'deletedAt', type: 'datetime', required: false },
      { key: 'createdAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'users_externalId_unique', type: 'unique', attributes: ['externalId'], orders: ['asc'] },
      { key: 'users_email_unique', type: 'unique', attributes: ['email'], orders: ['asc'] },
      { key: 'users_role_idx', type: 'key', attributes: ['role'], orders: ['asc'] },
      { key: 'users_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      { key: 'users_deletedAt_idx', type: 'key', attributes: ['deletedAt'], orders: ['desc'] },
      { key: 'users_email_search', type: 'fulltext', attributes: ['email'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'staff_profiles',
    name: 'Staff Profiles',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'userId', type: 'string', size: 255, required: true },
      { key: 'fullName', type: 'string', size: 255, required: true },
      { key: 'firstName', type: 'string', size: 100, required: false },
      { key: 'lastName', type: 'string', size: 100, required: false },
      { key: 'email', type: 'string', size: 320, required: false },
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'employeeNumber', type: 'string', size: 64, required: false },
      { key: 'username', type: 'string', size: 120, required: false },
      { key: 'department', type: 'string', size: 120, required: false },
      { key: 'role', type: 'string', size: 64, required: false },
      { key: 'phone', type: 'string', size: 32, required: false },
      { key: 'address', type: 'string', size: 2048, required: false },
      { key: 'licenseNumber', type: 'string', size: 100, required: false },
      { key: 'licenseExpiry', type: 'datetime', required: false },
      { key: 'siaLicence', type: 'string', size: 100, required: false },
      { key: 'siaExpiryDate', type: 'datetime', required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['active', 'inactive', 'suspended', 'pending_compliance'],
        required: true,
        default: 'active',
      },
      { key: 'dBSStatus', type: 'string', size: 64, required: false },
      { key: 'rightToWork', type: 'string', size: 64, required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'staff_profiles_userId_unique', type: 'unique', attributes: ['userId'], orders: ['asc'] },
      { key: 'staff_profiles_email_idx', type: 'key', attributes: ['email'], orders: ['asc'] },
      { key: 'staff_profiles_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      {
        key: 'staff_profiles_empno_unique',
        type: 'unique',
        attributes: ['employeeNumber'],
        orders: ['asc'],
      },
      {
        key: 'staff_profiles_username_unique',
        type: 'unique',
        attributes: ['username'],
        orders: ['asc'],
      },
      { key: 'staff_profiles_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'staff_profiles_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'staff_invites',
    name: 'Staff Invites',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'code', type: 'string', size: 64, required: true },
      { key: 'email', type: 'email', required: true },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'createdBy', type: 'string', size: 255, required: true },
      { key: 'createdAt', type: 'datetime', required: true },
      { key: 'expiresAt', type: 'datetime', required: true },
      {
        key: 'status',
        type: 'enum',
        elements: ['active', 'used', 'expired', 'revoked'],
        required: true,
        default: 'active',
      },
      { key: 'used_by', type: 'string', size: 255, required: false },
      { key: 'used_at', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'staff_invites_code_unique', type: 'unique', attributes: ['code'], orders: ['asc'] },
      { key: 'staff_invites_email_idx', type: 'key', attributes: ['email'], orders: ['asc'] },
      { key: 'staff_invites_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      { key: 'staff_invites_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'staff_invites_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      {
        key: 'staff_invites_expiry_idx',
        type: 'key',
        attributes: ['expiresAt'],
        orders: ['desc'],
      },
    ],
  },
  {
    collectionId: 'staff_numbers',
    name: 'Staff Numbers',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'staffId', type: 'string', size: 255, required: true },
      { key: 'employeeNumber', type: 'string', size: 64, required: true },
      { key: 'prefix', type: 'string', size: 16, required: false },
      { key: 'sequence', type: 'integer', required: false },
      { key: 'issuedAt', type: 'datetime', required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'allocated_at', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'staff_numbers_staffId_unique', type: 'unique', attributes: ['staffId'], orders: ['asc'] },
      {
        key: 'staff_numbers_empno_unique',
        type: 'unique',
        attributes: ['employeeNumber'],
        orders: ['asc'],
      },
    ],
  },
  {
    collectionId: 'clients',
    name: 'Clients',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'name', type: 'string', size: 255, required: true },
      { key: 'companyName', type: 'string', size: 255, required: true },
      { key: 'contactPerson', type: 'string', size: 255, required: true },
      { key: 'phone', type: 'string', size: 32, required: true },
      { key: 'email', type: 'string', size: 320, required: true },
      { key: 'address', type: 'string', size: 1024, required: false },
      { key: 'city', type: 'string', size: 120, required: false },
      { key: 'postcode', type: 'string', size: 32, required: false },
      { key: 'industry', type: 'string', size: 120, required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['active', 'inactive', 'pending'],
        required: true,
        default: 'active',
      },
      { key: 'contractStartDate', type: 'datetime', required: false },
      { key: 'contractEndDate', type: 'datetime', required: false },
      { key: 'contractValue', type: 'float', required: false },
      { key: 'siteLocations', type: 'string', size: 8192, required: false },
      { key: 'notes', type: 'string', size: 8192, required: false },
      { key: 'userId', type: 'string', size: 255, required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'clients_name_idx', type: 'key', attributes: ['name'], orders: ['asc'] },
      {
        key: 'clients_companyName_idx',
        type: 'key',
        attributes: ['companyName'],
        orders: ['asc'],
      },
      { key: 'clients_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      { key: 'clients_userId_idx', type: 'key', attributes: ['userId'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'sites',
    name: 'Sites',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteName', type: 'string', size: 255, required: true },
      { key: 'address', type: 'string', size: 1024, required: true },
      { key: 'city', type: 'string', size: 120, required: false },
      { key: 'postcode', type: 'string', size: 32, required: false },
      { key: 'gpsLat', type: 'float', required: false },
      { key: 'gpsLng', type: 'float', required: false },
      { key: 'siteNotes', type: 'string', size: 8192, required: false },
      { key: 'accessInstructions', type: 'string', size: 8192, required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['active', 'inactive'],
        required: true,
        default: 'active',
      },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'sites_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'sites_siteName_idx', type: 'key', attributes: ['siteName'], orders: ['asc'] },
      { key: 'sites_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'guards',
    name: 'Guards',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'firstName', type: 'string', size: 120, required: true },
      { key: 'lastName', type: 'string', size: 120, required: true },
      { key: 'email', type: 'string', size: 320, required: true },
      { key: 'phone', type: 'string', size: 32, required: true },
      { key: 'badgeNumber', type: 'string', size: 64, required: false },
      {
        key: 'role',
        type: 'enum',
        elements: ['guard', 'supervisor', 'team_leader'],
        required: true,
        default: 'guard',
      },
      { key: 'siaLicenceType', type: 'string', size: 120, required: false },
      { key: 'siaLicenceNumber', type: 'string', size: 120, required: false },
      { key: 'siaExpiryDate', type: 'datetime', required: false },
      { key: 'dbsStatus', type: 'string', size: 64, required: false },
      { key: 'dbsExpiryDate', type: 'datetime', required: false },
      { key: 'rightToWorkStatus', type: 'string', size: 64, required: false },
      { key: 'payRate', type: 'float', required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['active', 'inactive', 'suspended'],
        required: true,
        default: 'active',
      },
      { key: 'notes', type: 'string', size: 8192, required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'guards_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      { key: 'guards_email_idx', type: 'key', attributes: ['email'], orders: ['asc'] },
      { key: 'guards_role_idx', type: 'key', attributes: ['role'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'shifts',
    name: 'Shifts',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'shiftId', type: 'string', size: 255, required: false },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'siteId', type: 'string', size: 255, required: true },
      { key: 'date', type: 'datetime', required: true },
      { key: 'startTime', type: 'string', size: 64, required: true },
      { key: 'endTime', type: 'string', size: 64, required: true },
      { key: 'position', type: 'string', size: 255, required: false },
      { key: 'positionTitle', type: 'string', size: 255, required: false },
      { key: 'title', type: 'string', size: 255, required: false },
      { key: 'description', type: 'string', size: 8192, required: false },
      { key: 'requirements', type: 'string', size: 8192, required: false },
      { key: 'specialRequirements', type: 'string', size: 8192, required: false },
      { key: 'notes', type: 'string', size: 8192, required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['scheduled', 'confirmed', 'completed', 'cancelled', 'open', 'assigned', 'filled', 'unfilled', 'active'],
        required: true,
        default: 'scheduled',
      },
      {
        key: 'published',
        type: 'enum',
        elements: ['true', 'false'],
        required: true,
        default: 'false',
      },
      { key: 'guardId', type: 'string', size: 255, required: false },
      { key: 'assignedGuardId', type: 'string', size: 255, required: false },
      { key: 'assignedGuardName', type: 'string', size: 255, required: false },
      { key: 'staffId', type: 'string', size: 255, required: false },
      { key: 'positionsOpen', type: 'integer', required: false, default: 1 },
      { key: 'requiredHeadcount', type: 'integer', required: false, default: 1 },
      { key: 'minimumGradeRequired', type: 'integer', required: false, min: 1, max: 5 },
      { key: 'hourlyRate', type: 'float', required: false },
      { key: 'breakLength', type: 'integer', required: false },
      { key: 'createdBy', type: 'string', size: 255, required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'shifts_date_idx', type: 'key', attributes: ['date'], orders: ['asc'] },
      { key: 'shifts_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      { key: 'shifts_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      { key: 'shifts_startTime_idx', type: 'key', attributes: ['startTime'], orders: ['asc'] },
      { key: 'shifts_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'shift_assignments',
    name: 'Shift Assignments',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'shiftId', type: 'string', size: 255, required: true },
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteId', type: 'string', size: 255, required: true },
      { key: 'guardId', type: 'string', size: 255, required: true },
      { key: 'staffId', type: 'string', size: 255, required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['assigned', 'checked-in', 'completed', 'cancelled', 'pending'],
        required: true,
        default: 'assigned',
      },
      { key: 'assignedAt', type: 'datetime', required: false },
      { key: 'checkInTime', type: 'datetime', required: false },
      { key: 'checkOutTime', type: 'datetime', required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      {
        key: 'shift_assign_shiftId_idx',
        type: 'key',
        attributes: ['shiftId'],
        orders: ['asc'],
      },
      {
        key: 'shift_assign_clientId_idx',
        type: 'key',
        attributes: ['clientId'],
        orders: ['asc'],
      },
      {
        key: 'shift_assign_siteId_idx',
        type: 'key',
        attributes: ['siteId'],
        orders: ['asc'],
      },
      {
        key: 'shift_assign_guardId_idx',
        type: 'key',
        attributes: ['guardId'],
        orders: ['asc'],
      },
      {
        key: 'shift_assign_staffId_idx',
        type: 'key',
        attributes: ['staffId'],
        orders: ['asc'],
      },
    ],
  },
  {
    collectionId: 'audit_logs',
    name: 'Audit Logs',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'actorId', type: 'string', size: 255, required: false },
      { key: 'actorRole', type: 'string', size: 64, required: false },
      { key: 'action', type: 'string', size: 120, required: true },
      { key: 'resourceType', type: 'string', size: 120, required: false },
      { key: 'entity', type: 'string', size: 120, required: false },
      { key: 'entityType', type: 'string', size: 120, required: false },
      { key: 'entityId', type: 'string', size: 255, required: false },
      { key: 'actorUserId', type: 'string', size: 255, required: false },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'metadataJson', type: 'string', size: 32768, required: false },
      { key: 'diff', type: 'string', size: 32768, required: false },
      { key: 'ipAddress', type: 'string', size: 64, required: false },
      { key: 'userAgent', type: 'string', size: 1024, required: false },
      {
        key: 'driveSyncStatus',
        type: 'enum',
        elements: ['pending', 'failed', 'success', 'synced'],
        required: false,
        default: 'pending',
      },
      { key: 'createdAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'audit_logs_action_idx', type: 'key', attributes: ['action'], orders: ['asc'] },
      {
        key: 'audit_logs_resourceType_idx',
        type: 'key',
        attributes: ['resourceType'],
        orders: ['asc'],
      },
      {
        key: 'audit_logs_createdAt_idx',
        type: 'key',
        attributes: ['createdAt'],
        orders: ['desc'],
      },
      { key: 'audit_logs_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'audit_logs_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      { key: 'audit_logs_entity_idx', type: 'key', attributes: ['entity'], orders: ['asc'] },
      { key: 'audit_logs_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'compliance_wizard',
    name: 'Compliance Wizard',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'staffId', type: 'string', size: 255, required: true },
      { key: 'stepNumber', type: 'integer', required: true, min: 1, max: 7 },
      { key: 'stepData', type: 'json', required: true, size: 65535 },
      { key: 'templateKey', type: 'string', size: 255, required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['draft', 'submitted', 'approved', 'rejected'],
        required: true,
        default: 'draft',
      },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'compliance_wizard_staff_idx', type: 'key', attributes: ['staffId'], orders: ['asc'] },
      {
        key: 'compliance_wizard_step_idx',
        type: 'key',
        attributes: ['stepNumber'],
        orders: ['asc'],
      },
      {
        key: 'compliance_wizard_staff_step_unique',
        type: 'unique',
        attributes: ['staffId', 'stepNumber'],
        orders: ['asc', 'asc'],
      },
    ],
  },
  {
    collectionId: 'compliance_uploads',
    name: 'Compliance Uploads',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'staffId', type: 'string', size: 255, required: true },
      { key: 'fileId', type: 'string', size: 255, required: false },
      { key: 'fileName', type: 'string', size: 500, required: true },
      { key: 'fileType', type: 'string', size: 120, required: true },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'appwriteFileId', type: 'string', size: 255, required: false },
      { key: 'googleDriveFileId', type: 'string', size: 255, required: false },
      { key: 'googleDriveFolderId', type: 'string', size: 255, required: false },
      {
        key: 'driveSyncStatus',
        type: 'enum',
        elements: ['pending', 'failed', 'success'],
        required: true,
        default: 'pending',
      },
      {
        key: 'syncStatus',
        type: 'enum',
        elements: ['pending', 'failed', 'success', 'synced'],
        required: false,
        default: 'pending',
      },
      { key: 'syncAttempts', type: 'integer', required: false, default: 0 },
      { key: 'syncError', type: 'string', size: 2048, required: false },
      { key: 'lastSyncAttempt', type: 'datetime', required: false },
      { key: 'uploadedAt', type: 'datetime', required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },

      { key: 'staff_id', type: 'string', size: 255, required: false },
      { key: 'file_name', type: 'string', size: 500, required: false },
      { key: 'file_type', type: 'string', size: 120, required: false },
      { key: 'appwrite_file_id', type: 'string', size: 255, required: false },
      { key: 'google_drive_file_id', type: 'string', size: 255, required: false },
      {
        key: 'drive_sync_status',
        type: 'enum',
        elements: ['pending', 'failed', 'success'],
        required: false,
        default: 'pending',
      },
      { key: 'sync_error', type: 'string', size: 2048, required: false },
      { key: 'last_sync_attempt', type: 'datetime', required: false },
      { key: 'created_at', type: 'datetime', required: false },
      { key: 'updated_at', type: 'datetime', required: false },
    ],
    indexes: [
      {
        key: 'compliance_uploads_staffId_idx',
        type: 'key',
        attributes: ['staffId'],
        orders: ['asc'],
      },
      {
        key: 'compliance_uploads_appwriteFileId_idx',
        type: 'key',
        attributes: ['appwriteFileId'],
        orders: ['asc'],
      },
      {
        key: 'compliance_uploads_driveSyncStatus_idx',
        type: 'key',
        attributes: ['driveSyncStatus'],
        orders: ['asc'],
      },
      {
        key: 'compliance_uploads_clientId_idx',
        type: 'key',
        attributes: ['clientId'],
        orders: ['asc'],
      },
      {
        key: 'compliance_uploads_siteId_idx',
        type: 'key',
        attributes: ['siteId'],
        orders: ['asc'],
      },
      {
        key: 'compliance_uploads_syncStatus_idx',
        type: 'key',
        attributes: ['syncStatus'],
        orders: ['asc'],
      },
      {
        key: 'compliance_uploads_lastSyncAttempt_idx',
        type: 'key',
        attributes: ['lastSyncAttempt'],
        orders: ['desc'],
      },
    ],
  },
  {
    collectionId: 'staff_compliance',
    name: 'Staff Compliance',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'staffId', type: 'string', size: 255, required: true },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'staff_id', type: 'string', size: 255, required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['pending', 'in_progress', 'submitted', 'approved', 'rejected'],
        required: true,
        default: 'in_progress',
      },
      { key: 'currentStep', type: 'integer', required: true, min: 0, max: 7, default: 0 },
      { key: 'current_step', type: 'integer', required: false, min: 0, max: 7 },
      { key: 'step1Identity', type: 'json', required: false, size: 65535 },
      { key: 'step_1_identity', type: 'string', size: 65535, required: false },
      { key: 'step_2_employment', type: 'string', size: 65535, required: false },
      { key: 'step_3_evidence', type: 'string', size: 65535, required: false },
      { key: 'step_4_references', type: 'string', size: 65535, required: false },
      { key: 'step_5_criminal', type: 'string', size: 4096, required: false },
      { key: 'step_6_sia', type: 'string', size: 4096, required: false },
      { key: 'step_7_video', type: 'string', size: 4096, required: false },
      { key: 'submittedAt', type: 'datetime', required: false },
      { key: 'submitted_at', type: 'datetime', required: false },
      { key: 'approvedAt', type: 'datetime', required: false },
      { key: 'approved_at', type: 'datetime', required: false },
      { key: 'approvedBy', type: 'string', size: 255, required: false },
      { key: 'approved_by', type: 'string', size: 255, required: false },
      { key: 'rejectionReason', type: 'string', size: 2048, required: false },
      { key: 'rejection_reason', type: 'string', size: 2048, required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
      { key: 'created_at', type: 'datetime', required: false },
      { key: 'updated_at', type: 'datetime', required: false },
    ],
    indexes: [
      {
        key: 'staff_compliance_staffId_unique',
        type: 'unique',
        attributes: ['staffId'],
        orders: ['asc'],
      },
      { key: 'staff_compliance_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      {
        key: 'staff_compliance_currentStep_idx',
        type: 'key',
        attributes: ['currentStep'],
        orders: ['asc'],
      },
      {
        key: 'staff_compliance_updatedAt_idx',
        type: 'key',
        attributes: ['updatedAt'],
        orders: ['desc'],
      },
      { key: 'staff_compliance_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'staff_compliance_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'staff_grades',
    name: 'Staff Grades',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'staffId', type: 'string', size: 255, required: true },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'staff_id', type: 'string', size: 255, required: false },
      { key: 'overallGrade', type: 'integer', required: false, min: 1, max: 5 },
      { key: 'overall_grade', type: 'integer', required: false, min: 1, max: 5 },
      { key: 'categories', type: 'json', required: false, size: 32768 },
      { key: 'notes', type: 'string', size: 8192, required: false },
      { key: 'gradedBy', type: 'string', size: 255, required: false },
      { key: 'graded_by', type: 'string', size: 255, required: false },
      { key: 'gradedAt', type: 'datetime', required: false },
      { key: 'graded_at', type: 'datetime', required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['pending', 'graded'],
        required: false,
        default: 'pending',
      },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'staff_grades_staffId_unique', type: 'unique', attributes: ['staffId'], orders: ['asc'] },
      {
        key: 'staff_grades_overallGrade_idx',
        type: 'key',
        attributes: ['overallGrade'],
        orders: ['desc'],
      },
      { key: 'staff_grades_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'staff_grades_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      { key: 'staff_grades_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'admin_grading',
    name: 'Admin Grading',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'staffId', type: 'string', size: 255, required: true },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'staffName', type: 'string', size: 255, required: false },
      { key: 'staffEmail', type: 'string', size: 320, required: false },
      { key: 'grade', type: 'integer', required: false, min: 1, max: 5 },
      { key: 'criteria', type: 'json', required: false, size: 32768 },
      { key: 'comment', type: 'string', size: 8192, required: false },
      { key: 'notes', type: 'string', size: 8192, required: false },
      { key: 'categories', type: 'string', size: 32768, required: false },
      { key: 'gradedBy', type: 'string', size: 255, required: false },
      { key: 'gradedByName', type: 'string', size: 255, required: false },
      { key: 'gradedAt', type: 'datetime', required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['pending', 'graded'],
        required: false,
        default: 'pending',
      },
      { key: 'daysWithoutGrading', type: 'integer', required: false, default: 0 },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'admin_grading_staffId_unique', type: 'unique', attributes: ['staffId'], orders: ['asc'] },
      { key: 'admin_grading_grade_idx', type: 'key', attributes: ['grade'], orders: ['desc'] },
      { key: 'admin_grading_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      {
        key: 'admin_grading_gradedAt_idx',
        type: 'key',
        attributes: ['gradedAt'],
        orders: ['desc'],
      },
      { key: 'admin_grading_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'admin_grading_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'applications',
    name: 'Applications',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'guardId', type: 'string', size: 255, required: true },
      { key: 'guardName', type: 'string', size: 255, required: true },
      { key: 'shiftId', type: 'string', size: 255, required: true },
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteId', type: 'string', size: 255, required: true },
      { key: 'shiftDetails', type: 'json', required: true, size: 65535 },
      { key: 'eligibilityScore', type: 'json', required: true, size: 65535 },
      { key: 'message', type: 'string', size: 2000, required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['pending', 'approved', 'rejected', 'withdrawn', 'expired'],
        required: true,
        default: 'pending',
      },
      { key: 'appliedAt', type: 'datetime', required: true },
      { key: 'reviewedAt', type: 'datetime', required: false },
      { key: 'reviewedBy', type: 'string', size: 255, required: false },
      { key: 'reviewerName', type: 'string', size: 255, required: false },
      { key: 'reviewNotes', type: 'string', size: 4096, required: false },
      { key: 'rejectionReason', type: 'string', size: 255, required: false },
      { key: 'withdrawnAt', type: 'datetime', required: false },
      { key: 'withdrawalReason', type: 'string', size: 1024, required: false },
    ],
    indexes: [
      { key: 'applications_guardId_idx', type: 'key', attributes: ['guardId'], orders: ['asc'] },
      { key: 'applications_shiftId_idx', type: 'key', attributes: ['shiftId'], orders: ['asc'] },
      { key: 'applications_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'applications_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      { key: 'applications_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      {
        key: 'applications_appliedAt_idx',
        type: 'key',
        attributes: ['appliedAt'],
        orders: ['desc'],
      },
    ],
  },
];

export const COLLECTION_BY_ID = new Map(
  COLLECTION_DEFINITIONS.map((collection) => [collection.collectionId, collection])
);
