const AUTHENTICATED_RW = [
  'read("users")',
  'create("users")',
  'update("users")',
  'delete("users")',
];

export const COLLECTION_DEFINITIONS = [
  {
    collectionId: 'users',
    name: 'Users',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'externalId', type: 'string', size: 255, required: true },
      { key: 'email', type: 'string', size: 320, required: true },
      { key: 'phone', type: 'string', size: 32, required: false },
      {
        key: 'role',
        type: 'enum',
        elements: ['admin', 'manager', 'staff', 'client'],
        required: true,
        default: 'staff',
      },
      {
        key: 'status',
        type: 'enum',
        elements: ['active', 'suspended', 'compliance_blocked', 'archived'],
        required: true,
        default: 'active',
      },
      { key: 'metadata', type: 'json', required: false, size: 8192 },
      { key: 'lastLoginAt', type: 'datetime', required: false },
      { key: 'deletedAt', type: 'datetime', required: false },
      { key: 'createdAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'users_externalId_unique', type: 'unique', attributes: ['externalId'], orders: ['asc'] },
      { key: 'users_email_unique', type: 'unique', attributes: ['email'], orders: ['asc'] },
      { key: 'users_role_idx', type: 'key', attributes: ['role'], orders: ['asc'] },
      { key: 'users_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      { key: 'users_deletedAt_idx', type: 'key', attributes: ['deletedAt'], orders: ['desc'] },
      { key: 'users_email_search', type: 'fulltext', attributes: ['email'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'staff_profiles',
    name: 'Staff Profiles',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'userId', type: 'string', size: 255, required: true },
      { key: 'fullName', type: 'string', size: 255, required: true },
      { key: 'firstName', type: 'string', size: 100, required: false },
      { key: 'lastName', type: 'string', size: 100, required: false },
      { key: 'email', type: 'string', size: 320, required: false },
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'employeeNumber', type: 'string', size: 64, required: false },
      { key: 'username', type: 'string', size: 120, required: false },
      { key: 'department', type: 'string', size: 120, required: false },
      { key: 'role', type: 'string', size: 64, required: false },
      { key: 'phone', type: 'string', size: 32, required: false },
      { key: 'address', type: 'string', size: 2048, required: false },
      { key: 'licenseNumber', type: 'string', size: 100, required: false },
      { key: 'licenseExpiry', type: 'datetime', required: false },
      { key: 'siaLicence', type: 'string', size: 100, required: false },
      { key: 'siaExpiryDate', type: 'datetime', required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['active', 'inactive', 'suspended', 'pending_compliance'],
        required: true,
        default: 'active',
      },
      { key: 'dBSStatus', type: 'string', size: 64, required: false },
      { key: 'rightToWork', type: 'string', size: 64, required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'staff_profiles_userId_unique', type: 'unique', attributes: ['userId'], orders: ['asc'] },
      { key: 'staff_profiles_email_idx', type: 'key', attributes: ['email'], orders: ['asc'] },
      { key: 'staff_profiles_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      {
        key: 'staff_profiles_empno_unique',
        type: 'unique',
        attributes: ['employeeNumber'],
        orders: ['asc'],
      },
      {
        key: 'staff_profiles_username_unique',
        type: 'unique',
        attributes: ['username'],
        orders: ['asc'],
      },
      { key: 'staff_profiles_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'staff_profiles_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'manager_profiles',
    name: 'Manager Profiles',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'userId', type: 'string', size: 255, required: true },
      { key: 'fullName', type: 'string', size: 255, required: false },
      { key: 'email', type: 'email', required: false },
      { key: 'assignedClientIds', type: 'string', size: 255, required: false, array: true },
      { key: 'assignedSiteIds', type: 'string', size: 255, required: false, array: true },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'manager_profiles_userId_unique', type: 'unique', attributes: ['userId'], orders: ['asc'] },
      { key: 'manager_profiles_email_idx', type: 'key', attributes: ['email'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'staff_invites',
    name: 'Staff Invites',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'code', type: 'string', size: 64, required: true },
      { key: 'email', type: 'email', required: true },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'createdBy', type: 'string', size: 255, required: true },
      { key: 'createdAt', type: 'datetime', required: true },
      { key: 'expiresAt', type: 'datetime', required: true },
      {
        key: 'status',
        type: 'enum',
        elements: ['active', 'used', 'expired', 'revoked'],
        required: true,
        default: 'active',
      },
      { key: 'used_by', type: 'string', size: 255, required: false },
      { key: 'used_at', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'staff_invites_code_unique', type: 'unique', attributes: ['code'], orders: ['asc'] },
      { key: 'staff_invites_email_idx', type: 'key', attributes: ['email'], orders: ['asc'] },
      { key: 'staff_invites_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      { key: 'staff_invites_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'staff_invites_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      {
        key: 'staff_invites_expiry_idx',
        type: 'key',
        attributes: ['expiresAt'],
        orders: ['desc'],
      },
      {
        key: 'stinv_email_code_exp_idx',
        type: 'key',
        attributes: ['email', 'code', 'status', 'expiresAt'],
        orders: ['asc', 'asc', 'asc', 'desc'],
      },
    ],
  },
  {
    collectionId: 'staff_numbers',
    name: 'Staff Numbers',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'staffId', type: 'string', size: 255, required: true },
      { key: 'employeeNumber', type: 'string', size: 64, required: true },
      { key: 'prefix', type: 'string', size: 16, required: false },
      { key: 'sequence', type: 'integer', required: false },
      { key: 'issuedAt', type: 'datetime', required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'allocated_at', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'staff_numbers_staffId_unique', type: 'unique', attributes: ['staffId'], orders: ['asc'] },
      {
        key: 'staff_numbers_empno_unique',
        type: 'unique',
        attributes: ['employeeNumber'],
        orders: ['asc'],
      },
    ],
  },
  {
    collectionId: 'clients',
    name: 'Clients',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: false },
      { key: 'name', type: 'string', size: 255, required: true },
      { key: 'companyName', type: 'string', size: 255, required: true },
      { key: 'contactPerson', type: 'string', size: 255, required: true },
      { key: 'phone', type: 'string', size: 32, required: true },
      { key: 'email', type: 'string', size: 320, required: true },
      { key: 'address', type: 'string', size: 1024, required: false },
      { key: 'city', type: 'string', size: 120, required: false },
      { key: 'postcode', type: 'string', size: 32, required: false },
      { key: 'industry', type: 'string', size: 120, required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['active', 'inactive', 'pending'],
        required: true,
        default: 'active',
      },
      { key: 'contractStartDate', type: 'datetime', required: false },
      { key: 'contractEndDate', type: 'datetime', required: false },
      { key: 'contractValue', type: 'float', required: false },
      { key: 'siteLocations', type: 'string', size: 8192, required: false },
      { key: 'notes', type: 'string', size: 512, required: false },
      { key: 'userId', type: 'string', size: 255, required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'clients_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'clients_name_idx', type: 'key', attributes: ['name'], orders: ['asc'] },
      {
        key: 'clients_companyName_idx',
        type: 'key',
        attributes: ['companyName'],
        orders: ['asc'],
      },
      { key: 'clients_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      { key: 'clients_userId_idx', type: 'key', attributes: ['userId'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'sites',
    name: 'Sites',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: false },
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteName', type: 'string', size: 255, required: true },
      { key: 'address', type: 'string', size: 1024, required: true },
      { key: 'city', type: 'string', size: 120, required: false },
      { key: 'postcode', type: 'string', size: 32, required: false },
      { key: 'gpsLat', type: 'float', required: false },
      { key: 'gpsLng', type: 'float', required: false },
      { key: 'siteNotes', type: 'string', size: 8192, required: false },
      { key: 'accessInstructions', type: 'string', size: 4096, required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['active', 'inactive'],
        required: true,
        default: 'active',
      },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'sites_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'sites_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'sites_siteName_idx', type: 'key', attributes: ['siteName'], orders: ['asc'] },
      { key: 'sites_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'posts',
    name: 'Posts',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'siteId', type: 'string', size: 255, required: true },
      { key: 'postName', type: 'string', size: 255, required: true },
      { key: 'postType', type: 'string', size: 255, required: false },
      { key: 'requirements', type: 'string', size: 8192, required: false },
      { key: 'riskLevel', type: 'string', size: 128, required: false },
      { key: 'status', type: 'string', size: 64, required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'posts_site_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      { key: 'posts_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      { key: 'posts_name_idx', type: 'key', attributes: ['postName'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'guards',
    name: 'Guards',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'firstName', type: 'string', size: 120, required: true },
      { key: 'lastName', type: 'string', size: 120, required: true },
      { key: 'email', type: 'string', size: 320, required: true },
      { key: 'phone', type: 'string', size: 32, required: true },
      { key: 'badgeNumber', type: 'string', size: 64, required: false },
      {
        key: 'role',
        type: 'enum',
        elements: ['guard', 'supervisor', 'team_leader'],
        required: true,
        default: 'guard',
      },
      { key: 'siaLicenceType', type: 'string', size: 120, required: false },
      { key: 'siaLicenceNumber', type: 'string', size: 120, required: false },
      { key: 'siaExpiryDate', type: 'datetime', required: false },
      { key: 'dbsStatus', type: 'string', size: 64, required: false },
      { key: 'dbsExpiryDate', type: 'datetime', required: false },
      { key: 'rightToWorkStatus', type: 'string', size: 64, required: false },
      {
        key: 'employmentType',
        type: 'enum',
        elements: ['PAYE', 'SELF_EMPLOYED'],
        required: false,
        default: 'PAYE',
      },
      { key: 'payRate', type: 'float', required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['active', 'inactive', 'suspended'],
        required: true,
        default: 'active',
      },
      { key: 'notes', type: 'string', size: 8192, required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'guards_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      { key: 'guards_email_idx', type: 'key', attributes: ['email'], orders: ['asc'] },
      { key: 'guards_role_idx', type: 'key', attributes: ['role'], orders: ['asc'] },
      { key: 'guards_employmentType_idx', type: 'key', attributes: ['employmentType'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'shifts',
    name: 'Shifts',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'shiftId', type: 'string', size: 255, required: false },
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteId', type: 'string', size: 255, required: true },
      { key: 'date', type: 'datetime', required: true },
      { key: 'startTime', type: 'string', size: 64, required: true },
      { key: 'endTime', type: 'string', size: 64, required: true },
      { key: 'position', type: 'string', size: 255, required: false },
      { key: 'positionTitle', type: 'string', size: 255, required: false },
      { key: 'title', type: 'string', size: 255, required: false },
      { key: 'description', type: 'string', size: 8192, required: false },
      { key: 'requirements', type: 'string', size: 2048, required: false },
      { key: 'specialRequirements', type: 'string', size: 2048, required: false },
      { key: 'notes', type: 'string', size: 255, required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['scheduled', 'confirmed', 'completed', 'cancelled', 'open', 'assigned', 'filled', 'unfilled', 'active'],
        required: true,
        default: 'scheduled',
      },
      {
        key: 'published',
        type: 'enum',
        elements: ['true', 'false'],
        required: true,
        default: 'false',
      },
      { key: 'guardId', type: 'string', size: 255, required: false },
      { key: 'assignedGuardId', type: 'string', size: 255, required: false },
      { key: 'assignedGuardName', type: 'string', size: 255, required: false },
      { key: 'staffId', type: 'string', size: 255, required: false },
      { key: 'positionsOpen', type: 'integer', required: false, default: 1 },
      { key: 'requiredHeadcount', type: 'integer', required: false, default: 1 },
      { key: 'minimumGradeRequired', type: 'integer', required: false, min: 1, max: 5 },
      { key: 'hourlyRate', type: 'float', required: false },
      { key: 'breakLength', type: 'integer', required: false },
      { key: 'createdBy', type: 'string', size: 255, required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'shifts_date_idx', type: 'key', attributes: ['date'], orders: ['asc'] },
      { key: 'shifts_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      { key: 'shifts_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      { key: 'shifts_startTime_idx', type: 'key', attributes: ['startTime'], orders: ['asc'] },
      { key: 'shifts_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      {
        key: 'shifts_client_site_date_status_idx',
        type: 'key',
        attributes: ['clientId', 'siteId', 'date', 'status'],
        orders: ['asc', 'asc', 'desc', 'asc'],
      },
    ],
  },
  {
    collectionId: 'shift_assignments',
    name: 'Shift Assignments',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'shiftId', type: 'string', size: 255, required: true },
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteId', type: 'string', size: 255, required: true },
      { key: 'guardId', type: 'string', size: 255, required: true },
      { key: 'staffId', type: 'string', size: 255, required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['assigned', 'checked-in', 'completed', 'cancelled', 'pending'],
        required: true,
        default: 'assigned',
      },
      { key: 'assignedAt', type: 'datetime', required: false },
      { key: 'checkInTime', type: 'datetime', required: false },
      { key: 'checkOutTime', type: 'datetime', required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      {
        key: 'shift_assign_shiftId_idx',
        type: 'key',
        attributes: ['shiftId'],
        orders: ['asc'],
      },
      {
        key: 'shift_assign_clientId_idx',
        type: 'key',
        attributes: ['clientId'],
        orders: ['asc'],
      },
      {
        key: 'shift_assign_siteId_idx',
        type: 'key',
        attributes: ['siteId'],
        orders: ['asc'],
      },
      {
        key: 'shift_assign_guardId_idx',
        type: 'key',
        attributes: ['guardId'],
        orders: ['asc'],
      },
      {
        key: 'shift_assign_staffId_idx',
        type: 'key',
        attributes: ['staffId'],
        orders: ['asc'],
      },
    ],
  },
  {
    collectionId: 'recurring_patterns',
    name: 'Recurring Patterns',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'name', type: 'string', size: 255, required: true },
      { key: 'description', type: 'string', size: 4096, required: false },
      {
        key: 'frequency',
        type: 'enum',
        elements: ['daily', 'weekly', 'biweekly', 'monthly', 'custom'],
        required: true,
      },
      { key: 'interval', type: 'integer', required: true, min: 1, max: 365 },
      { key: 'daysOfWeek', type: 'integer', required: false, array: true, min: 0, max: 6 },
      { key: 'startTime', type: 'string', size: 32, required: true },
      { key: 'endTime', type: 'string', size: 32, required: true },
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteId', type: 'string', size: 255, required: true },
      { key: 'positionType', type: 'string', size: 255, required: false },
      { key: 'requiredGuards', type: 'integer', required: false, min: 1, max: 999 },
      { key: 'specialInstructions', type: 'string', size: 8192, required: false },
      {
        key: 'endCondition',
        type: 'enum',
        elements: ['never', 'after_occurrences', 'on_date'],
        required: true,
      },
      { key: 'occurrences', type: 'integer', required: false, min: 1, max: 10000 },
      { key: 'endDate', type: 'datetime', required: false },
      { key: 'isActive', type: 'boolean', required: false, default: true },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'recp_active_idx', type: 'key', attributes: ['isActive'], orders: ['asc'] },
      { key: 'recp_client_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'recp_site_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      { key: 'recp_freq_idx', type: 'key', attributes: ['frequency'], orders: ['asc'] },
      { key: 'recp_created_idx', type: 'key', attributes: ['createdAt'], orders: ['desc'] },
    ],
  },
  {
    collectionId: 'audit_logs',
    name: 'Audit Logs',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'actorId', type: 'string', size: 255, required: false },
      { key: 'actorRole', type: 'string', size: 64, required: false },
      { key: 'action', type: 'string', size: 120, required: true },
      { key: 'resourceType', type: 'string', size: 120, required: false },
      { key: 'entity', type: 'string', size: 120, required: false },
      { key: 'entityType', type: 'string', size: 120, required: false },
      { key: 'entityId', type: 'string', size: 255, required: false },
      { key: 'actorUserId', type: 'string', size: 255, required: false },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'metadataJson', type: 'string', size: 32768, required: false },
      { key: 'diff', type: 'string', size: 32768, required: false },
      { key: 'ipAddress', type: 'string', size: 64, required: false },
      { key: 'userAgent', type: 'string', size: 1024, required: false },
      {
        key: 'driveSyncStatus',
        type: 'enum',
        elements: ['pending', 'failed', 'success', 'synced'],
        required: false,
        default: 'pending',
      },
      { key: 'createdAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'audit_logs_action_idx', type: 'key', attributes: ['action'], orders: ['asc'] },
      {
        key: 'audit_logs_resourceType_idx',
        type: 'key',
        attributes: ['resourceType'],
        orders: ['asc'],
      },
      {
        key: 'audit_logs_createdAt_idx',
        type: 'key',
        attributes: ['createdAt'],
        orders: ['desc'],
      },
      { key: 'audit_logs_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'audit_logs_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      { key: 'audit_logs_entity_idx', type: 'key', attributes: ['entity'], orders: ['asc'] },
      { key: 'audit_logs_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'compliance_wizard',
    name: 'Compliance Wizard',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'staffId', type: 'string', size: 255, required: true },
      { key: 'stepNumber', type: 'integer', required: true, min: 1, max: 7 },
      { key: 'stepData', type: 'json', required: true, size: 65535 },
      { key: 'templateKey', type: 'string', size: 255, required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['draft', 'submitted', 'approved', 'rejected'],
        required: true,
        default: 'draft',
      },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'compliance_wizard_staff_idx', type: 'key', attributes: ['staffId'], orders: ['asc'] },
      {
        key: 'compliance_wizard_step_idx',
        type: 'key',
        attributes: ['stepNumber'],
        orders: ['asc'],
      },
      {
        key: 'compliance_wizard_staff_step_unique',
        type: 'unique',
        attributes: ['staffId', 'stepNumber'],
        orders: ['asc', 'asc'],
      },
    ],
  },
  {
    collectionId: 'compliance_uploads',
    name: 'Compliance Uploads',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'staffId', type: 'string', size: 255, required: true },
      { key: 'guardId', type: 'string', size: 255, required: false },
      { key: 'fileId', type: 'string', size: 255, required: false },
      { key: 'fileName', type: 'string', size: 500, required: true },
      { key: 'fileType', type: 'string', size: 120, required: true },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'appwriteFileId', type: 'string', size: 255, required: false },
      { key: 'googleDriveFileId', type: 'string', size: 255, required: false },
      { key: 'googleDriveFolderId', type: 'string', size: 255, required: false },
      {
        key: 'driveSyncStatus',
        type: 'enum',
        elements: ['pending', 'failed', 'success'],
        required: true,
        default: 'pending',
      },
      {
        key: 'syncStatus',
        type: 'enum',
        elements: ['pending', 'failed', 'success', 'synced'],
        required: false,
        default: 'pending',
      },
      {
        key: 'status',
        type: 'enum',
        elements: ['pending', 'submitted', 'approved', 'rejected', 'archived'],
        required: false,
        default: 'pending',
      },
      { key: 'syncAttempts', type: 'integer', required: false, default: 0 },
      { key: 'syncError', type: 'string', size: 2048, required: false },
      { key: 'lastSyncAttempt', type: 'datetime', required: false },
      { key: 'uploadedAt', type: 'datetime', required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },

      { key: 'staff_id', type: 'string', size: 255, required: false },
      { key: 'file_name', type: 'string', size: 500, required: false },
      { key: 'file_type', type: 'string', size: 120, required: false },
      { key: 'appwrite_file_id', type: 'string', size: 255, required: false },
      { key: 'google_drive_file_id', type: 'string', size: 255, required: false },
      {
        key: 'drive_sync_status',
        type: 'enum',
        elements: ['pending', 'failed', 'success'],
        required: false,
        default: 'pending',
      },
      { key: 'sync_error', type: 'string', size: 2048, required: false },
      { key: 'last_sync_attempt', type: 'datetime', required: false },
      { key: 'created_at', type: 'datetime', required: false },
      { key: 'updated_at', type: 'datetime', required: false },
    ],
    indexes: [
      {
        key: 'compliance_uploads_staffId_idx',
        type: 'key',
        attributes: ['staffId'],
        orders: ['asc'],
      },
      {
        key: 'compliance_uploads_guardId_idx',
        type: 'key',
        attributes: ['guardId'],
        orders: ['asc'],
      },
      {
        key: 'cup_appfile_idx',
        type: 'key',
        attributes: ['appwriteFileId'],
        orders: ['asc'],
      },
      {
        key: 'cup_dsync_idx',
        type: 'key',
        attributes: ['driveSyncStatus'],
        orders: ['asc'],
      },
      {
        key: 'cup_dsync_snk_idx',
        type: 'key',
        attributes: ['drive_sync_status'],
        orders: ['asc'],
      },
      {
        key: 'compliance_uploads_clientId_idx',
        type: 'key',
        attributes: ['clientId'],
        orders: ['asc'],
      },
      {
        key: 'compliance_uploads_siteId_idx',
        type: 'key',
        attributes: ['siteId'],
        orders: ['asc'],
      },
      {
        key: 'compliance_uploads_syncStatus_idx',
        type: 'key',
        attributes: ['syncStatus'],
        orders: ['asc'],
      },
      {
        key: 'compliance_uploads_status_idx',
        type: 'key',
        attributes: ['status'],
        orders: ['asc'],
      },
      {
        key: 'compliance_uploads_createdAt_idx',
        type: 'key',
        attributes: ['createdAt'],
        orders: ['desc'],
      },
      {
        key: 'cup_lastsync_idx',
        type: 'key',
        attributes: ['lastSyncAttempt'],
        orders: ['desc'],
      },
      {
        key: 'cup_guard_stat_ct_idx',
        type: 'key',
        attributes: ['guardId', 'drive_sync_status', 'status', 'createdAt'],
        orders: ['asc', 'asc', 'asc', 'desc'],
      },
    ],
  },
  {
    collectionId: 'staff_compliance',
    name: 'Staff Compliance',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'staffId', type: 'string', size: 255, required: true },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'staff_id', type: 'string', size: 255, required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['pending', 'in_progress', 'submitted', 'approved', 'rejected'],
        required: true,
        default: 'in_progress',
      },
      { key: 'currentStep', type: 'integer', required: true, min: 0, max: 7, default: 0 },
      { key: 'current_step', type: 'integer', required: false, min: 0, max: 7 },
      { key: 'step1Identity', type: 'json', required: false, size: 65535 },
      { key: 'step_1_identity', type: 'string', size: 65535, required: false },
      { key: 'step_2_employment', type: 'string', size: 65535, required: false },
      { key: 'step_3_evidence', type: 'string', size: 65535, required: false },
      { key: 'step_4_references', type: 'string', size: 65535, required: false },
      { key: 'step_5_criminal', type: 'string', size: 4096, required: false },
      { key: 'step_6_sia', type: 'string', size: 4096, required: false },
      { key: 'step_7_video', type: 'string', size: 4096, required: false },
      { key: 'submittedAt', type: 'datetime', required: false },
      { key: 'submitted_at', type: 'datetime', required: false },
      { key: 'approvedAt', type: 'datetime', required: false },
      { key: 'approved_at', type: 'datetime', required: false },
      { key: 'approvedBy', type: 'string', size: 255, required: false },
      { key: 'approved_by', type: 'string', size: 255, required: false },
      { key: 'rejectionReason', type: 'string', size: 512, required: false },
      { key: 'rejection_reason', type: 'string', size: 512, required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
      { key: 'created_at', type: 'datetime', required: false },
      { key: 'updated_at', type: 'datetime', required: false },
    ],
    indexes: [
      {
        key: 'staff_compliance_staffId_unique',
        type: 'unique',
        attributes: ['staffId'],
        orders: ['asc'],
      },
      { key: 'staff_compliance_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      {
        key: 'staff_compliance_currentStep_idx',
        type: 'key',
        attributes: ['currentStep'],
        orders: ['asc'],
      },
      {
        key: 'staff_compliance_updatedAt_idx',
        type: 'key',
        attributes: ['updatedAt'],
        orders: ['desc'],
      },
      { key: 'staff_compliance_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'staff_compliance_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'staff_grades',
    name: 'Staff Grades',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'staffId', type: 'string', size: 255, required: true },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'staff_id', type: 'string', size: 255, required: false },
      { key: 'overallGrade', type: 'integer', required: false, min: 1, max: 5 },
      { key: 'overall_grade', type: 'integer', required: false, min: 1, max: 5 },
      { key: 'categories', type: 'json', required: false, size: 32768 },
      { key: 'notes', type: 'string', size: 8192, required: false },
      { key: 'gradedBy', type: 'string', size: 255, required: false },
      { key: 'graded_by', type: 'string', size: 255, required: false },
      { key: 'gradedAt', type: 'datetime', required: false },
      { key: 'graded_at', type: 'datetime', required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['pending', 'graded'],
        required: false,
        default: 'pending',
      },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'staff_grades_staffId_unique', type: 'unique', attributes: ['staffId'], orders: ['asc'] },
      {
        key: 'staff_grades_overallGrade_idx',
        type: 'key',
        attributes: ['overallGrade'],
        orders: ['desc'],
      },
      { key: 'staff_grades_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'staff_grades_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      { key: 'staff_grades_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'admin_grading',
    name: 'Admin Grading',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'staffId', type: 'string', size: 255, required: true },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'staffName', type: 'string', size: 255, required: false },
      { key: 'staffEmail', type: 'string', size: 320, required: false },
      { key: 'grade', type: 'integer', required: false, min: 1, max: 5 },
      { key: 'criteria', type: 'json', required: false, size: 32768 },
      { key: 'comment', type: 'string', size: 8192, required: false },
      { key: 'notes', type: 'string', size: 2048, required: false },
      { key: 'categories', type: 'string', size: 32768, required: false },
      { key: 'gradedBy', type: 'string', size: 255, required: false },
      { key: 'gradedByName', type: 'string', size: 255, required: false },
      { key: 'gradedAt', type: 'datetime', required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['pending', 'graded'],
        required: false,
        default: 'pending',
      },
      { key: 'daysWithoutGrading', type: 'integer', required: false, default: 0 },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'admin_grading_staffId_unique', type: 'unique', attributes: ['staffId'], orders: ['asc'] },
      { key: 'admin_grading_grade_idx', type: 'key', attributes: ['grade'], orders: ['desc'] },
      { key: 'admin_grading_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      {
        key: 'admin_grading_gradedAt_idx',
        type: 'key',
        attributes: ['gradedAt'],
        orders: ['desc'],
      },
      { key: 'admin_grading_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'admin_grading_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'timesheets',
    name: 'Timesheets',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'guardId', type: 'string', size: 255, required: true },
      { key: 'weekStart', type: 'datetime', required: true },
      { key: 'weekEnd', type: 'datetime', required: true },
      {
        key: 'status',
        type: 'enum',
        elements: ['open', 'submitted', 'approved', 'rejected', 'locked'],
        required: true,
        default: 'open',
      },
      { key: 'submittedAt', type: 'datetime', required: false },
      { key: 'submittedBy', type: 'string', size: 255, required: false },
      { key: 'approvedAt', type: 'datetime', required: false },
      { key: 'approvedBy', type: 'string', size: 255, required: false },
      { key: 'rejectedAt', type: 'datetime', required: false },
      { key: 'rejectedBy', type: 'string', size: 255, required: false },
      { key: 'rejectionReason', type: 'string', size: 2048, required: false },
      { key: 'totalMinutes', type: 'integer', required: false, default: 0, min: 0 },
      { key: 'totalPayMinutes', type: 'integer', required: false, default: 0, min: 0 },
      { key: 'clientBreakdown', type: 'json', required: false, size: 65535 },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'timesheets_guardId_idx', type: 'key', attributes: ['guardId'], orders: ['asc'] },
      {
        key: 'timesheets_guard_week_idx',
        type: 'key',
        attributes: ['guardId', 'weekStart'],
        orders: ['asc', 'desc'],
      },
      { key: 'timesheets_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      { key: 'timesheets_weekStart_idx', type: 'key', attributes: ['weekStart'], orders: ['desc'] },
      { key: 'timesheets_approvedAt_idx', type: 'key', attributes: ['approvedAt'], orders: ['desc'] },
    ],
  },
  {
    collectionId: 'timesheet_entries',
    name: 'Timesheet Entries',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'timesheetId', type: 'string', size: 255, required: true },
      { key: 'guardId', type: 'string', size: 255, required: true },
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteId', type: 'string', size: 255, required: true },
      { key: 'shiftId', type: 'string', size: 255, required: false },
      { key: 'workDate', type: 'datetime', required: true },
      { key: 'startAt', type: 'datetime', required: true },
      { key: 'endAt', type: 'datetime', required: false },
      { key: 'breakMinutes', type: 'integer', required: false, default: 0, min: 0 },
      { key: 'minutesWorked', type: 'integer', required: false, default: 0, min: 0 },
      { key: 'minutesPayable', type: 'integer', required: false, default: 0, min: 0 },
      {
        key: 'source',
        type: 'enum',
        elements: ['gps_clock', 'manual', 'imported'],
        required: true,
        default: 'manual',
      },
      { key: 'gpsMeta', type: 'json', required: false, size: 65535 },
      {
        key: 'status',
        type: 'enum',
        elements: ['open', 'submitted', 'approved', 'rejected'],
        required: true,
        default: 'open',
      },
      { key: 'approvedAt', type: 'datetime', required: false },
      { key: 'approvedBy', type: 'string', size: 255, required: false },
      { key: 'rejectionReason', type: 'string', size: 2048, required: false },
      { key: 'notes', type: 'string', size: 4096, required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      {
        key: 'timesheet_entries_timesheetId_idx',
        type: 'key',
        attributes: ['timesheetId'],
        orders: ['asc'],
      },
      {
        key: 'timesheet_entries_guardId_idx',
        type: 'key',
        attributes: ['guardId'],
        orders: ['asc'],
      },
      {
        key: 'tsent_client_site_wd_idx',
        type: 'key',
        attributes: ['clientId', 'siteId', 'workDate'],
        orders: ['asc', 'asc', 'desc'],
      },
      {
        key: 'timesheet_entries_shiftId_idx',
        type: 'key',
        attributes: ['shiftId'],
        orders: ['asc'],
      },
      {
        key: 'timesheet_entries_status_idx',
        type: 'key',
        attributes: ['status'],
        orders: ['asc'],
      },
      {
        key: 'timesheet_entries_startAt_idx',
        type: 'key',
        attributes: ['startAt'],
        orders: ['desc'],
      },
    ],
  },
  {
    collectionId: 'payroll_exports',
    name: 'Payroll Exports',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: false },
      { key: 'runBy', type: 'string', size: 255, required: true },
      { key: 'rangeStart', type: 'datetime', required: true },
      { key: 'rangeEnd', type: 'datetime', required: true },
      { key: 'filters', type: 'json', required: false, size: 65535 },
      { key: 'fileId', type: 'string', size: 255, required: false },
      { key: 'createdAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'payroll_exports_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'payroll_exports_createdAt_idx', type: 'key', attributes: ['createdAt'], orders: ['desc'] },
      { key: 'payroll_exports_runBy_idx', type: 'key', attributes: ['runBy'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'billing_exports',
    name: 'Billing Exports',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: false },
      { key: 'runBy', type: 'string', size: 255, required: true },
      { key: 'rangeStart', type: 'datetime', required: true },
      { key: 'rangeEnd', type: 'datetime', required: true },
      { key: 'filters', type: 'json', required: false, size: 65535 },
      { key: 'fileId', type: 'string', size: 255, required: false },
      { key: 'createdAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'billing_exports_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'billing_exports_createdAt_idx', type: 'key', attributes: ['createdAt'], orders: ['desc'] },
      { key: 'billing_exports_runBy_idx', type: 'key', attributes: ['runBy'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'rate_cards',
    name: 'Rate Cards',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: false },
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'role', type: 'string', size: 120, required: false },
      {
        key: 'dayType',
        type: 'enum',
        elements: ['weekday', 'weekend', 'bank_holiday', 'night'],
        required: false,
      },
      { key: 'hourlyRate', type: 'float', required: true, min: 0 },
      { key: 'vatRule', type: 'string', size: 255, required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'rate_cards_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'rate_cards_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      { key: 'rate_cards_role_idx', type: 'key', attributes: ['role'], orders: ['asc'] },
      { key: 'rate_cards_dayType_idx', type: 'key', attributes: ['dayType'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'compliance_rules',
    name: 'Compliance Rules',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      {
        key: 'type',
        type: 'enum',
        elements: ['sia', 'id', 'right_to_work', 'dbs', 'other'],
        required: true,
      },
      { key: 'warnDays', type: 'json', required: false, size: 2048 },
      { key: 'escalationDays', type: 'integer', required: false, default: 7, min: 1, max: 365 },
      { key: 'enabled', type: 'boolean', required: true, default: true },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'compliance_rules_type_idx', type: 'key', attributes: ['type'], orders: ['asc'] },
      { key: 'compliance_rules_enabled_idx', type: 'key', attributes: ['enabled'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'compliance_flags',
    name: 'Compliance Flags',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'guardId', type: 'string', size: 255, required: true },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'siteId', type: 'string', size: 255, required: false },
      {
        key: 'type',
        type: 'enum',
        elements: ['sia', 'id', 'right_to_work', 'dbs', 'other'],
        required: true,
      },
      {
        key: 'severity',
        type: 'enum',
        elements: ['info', 'warning', 'critical'],
        required: true,
      },
      { key: 'dueAt', type: 'datetime', required: true },
      {
        key: 'status',
        type: 'enum',
        elements: ['open', 'resolved', 'dismissed'],
        required: true,
        default: 'open',
      },
      { key: 'lastNotifiedAt', type: 'datetime', required: false },
      { key: 'notes', type: 'string', size: 4096, required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'compliance_flags_guardId_idx', type: 'key', attributes: ['guardId'], orders: ['asc'] },
      { key: 'compliance_flags_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      { key: 'compliance_flags_type_idx', type: 'key', attributes: ['type'], orders: ['asc'] },
      { key: 'compliance_flags_dueAt_idx', type: 'key', attributes: ['dueAt'], orders: ['asc'] },
      { key: 'compliance_flags_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'compliance_flags_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'incidents',
    name: 'Incidents',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteId', type: 'string', size: 255, required: true },
      { key: 'shiftId', type: 'string', size: 255, required: false },
      { key: 'reportedBy', type: 'string', size: 255, required: true },
      {
        key: 'status',
        type: 'enum',
        elements: ['draft', 'submitted', 'interim_sent', 'needs_review', 'approved', 'final_sent', 'rejected'],
        required: true,
        default: 'draft',
      },
      {
        key: 'severity',
        type: 'enum',
        elements: ['low', 'medium', 'high', 'critical'],
        required: false,
        default: 'medium',
      },
      { key: 'summary', type: 'string', size: 500, required: true },
      { key: 'details', type: 'string', size: 32768, required: false },
      { key: 'reviewReason', type: 'string', size: 4096, required: false },
      { key: 'createdAt', type: 'datetime', required: true },
      { key: 'updatedAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'incidents_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'incidents_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      { key: 'incidents_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      { key: 'incidents_createdAt_idx', type: 'key', attributes: ['createdAt'], orders: ['desc'] },
    ],
  },
  {
    collectionId: 'assets',
    name: 'Assets',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'assetName', type: 'string', size: 255, required: true },
      { key: 'assetType', type: 'string', size: 255, required: false },
      { key: 'category', type: 'string', size: 255, required: false },
      { key: 'assetId', type: 'string', size: 255, required: true },
      { key: 'serialNumber', type: 'string', size: 255, required: false },
      { key: 'manufacturer', type: 'string', size: 255, required: false },
      { key: 'model', type: 'string', size: 255, required: false },
      { key: 'purchaseDate', type: 'string', size: 64, required: false },
      { key: 'purchaseCost', type: 'string', size: 64, required: false },
      { key: 'currentValue', type: 'string', size: 64, required: false },
      { key: 'status', type: 'string', size: 64, required: false },
      { key: 'condition', type: 'string', size: 64, required: false },
      { key: 'assignedTo', type: 'string', size: 255, required: false },
      { key: 'assignedDate', type: 'string', size: 64, required: false },
      { key: 'locationSiteId', type: 'string', size: 255, required: false },
      { key: 'storageLocation', type: 'string', size: 255, required: false },
      { key: 'warrantyExpiry', type: 'string', size: 64, required: false },
      { key: 'lastMaintenanceDate', type: 'string', size: 64, required: false },
      { key: 'nextMaintenanceDate', type: 'string', size: 64, required: false },
      { key: 'maintenanceNotes', type: 'string', size: 8192, required: false },
      { key: 'notes', type: 'string', size: 2048, required: false },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'assets_assetId_uq', type: 'unique', attributes: ['assetId'], orders: ['asc'] },
      { key: 'assets_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      { key: 'assets_cat_idx', type: 'key', attributes: ['category'], orders: ['asc'] },
      { key: 'assets_site_idx', type: 'key', attributes: ['locationSiteId'], orders: ['asc'] },
      { key: 'assets_assigned_idx', type: 'key', attributes: ['assignedTo'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'contracts',
    name: 'Contracts',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: false },
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'name', type: 'string', size: 255, required: true },
      { key: 'status', type: 'string', size: 64, required: false },
      { key: 'startDate', type: 'datetime', required: false },
      { key: 'endDate', type: 'datetime', required: false },
      { key: 'autoRenew', type: 'boolean', required: false, default: false },
      { key: 'renewalNoticeDays', type: 'integer', required: false, default: 90, min: 1, max: 365 },
      { key: 'lastReviewAt', type: 'datetime', required: false },
      { key: 'healthScore', type: 'float', required: false, min: 0, max: 1 },
      { key: 'createdAt', type: 'datetime', required: false },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'contracts_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'contracts_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'contracts_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      { key: 'contracts_endDate_idx', type: 'key', attributes: ['endDate'], orders: ['asc'] },
      { key: 'contracts_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'legal_entities',
    name: 'Legal Entities',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'name', type: 'string', size: 255, required: true },
      { key: 'entityType', type: 'enum', elements: ['holding', 'operating', 'subsidiary'], required: true },
      { key: 'registrationNumber', type: 'string', size: 128, required: false },
      { key: 'taxNumber', type: 'string', size: 128, required: false },
      { key: 'bankDetails', type: 'json', required: false, size: 65535 },
      { key: 'active', type: 'boolean', required: true, default: true },
      { key: 'createdAt', type: 'datetime', required: true },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'legal_entities_entityType_idx', type: 'key', attributes: ['entityType'], orders: ['asc'] },
      { key: 'legal_entities_active_idx', type: 'key', attributes: ['active'], orders: ['asc'] },
      { key: 'legal_entities_createdAt_idx', type: 'key', attributes: ['createdAt'], orders: ['desc'] },
    ],
  },
  {
    collectionId: 'profit_snapshots',
    name: 'Profit Snapshots',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: true },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'periodStart', type: 'datetime', required: true },
      { key: 'periodEnd', type: 'datetime', required: true },
      { key: 'workedHours', type: 'float', required: true },
      { key: 'revenue', type: 'float', required: true },
      { key: 'cost', type: 'float', required: true },
      { key: 'grossProfit', type: 'float', required: true },
      { key: 'grossMarginPct', type: 'float', required: true },
      { key: 'generatedAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'profit_snapshots_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'profit_snapshots_periodStart_idx', type: 'key', attributes: ['periodStart'], orders: ['desc'] },
      { key: 'profit_snapshots_generatedAt_idx', type: 'key', attributes: ['generatedAt'], orders: ['desc'] },
      { key: 'profit_snapshots_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'profit_snapshots_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'acquisition_targets',
    name: 'Acquisition Targets',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: true },
      { key: 'name', type: 'string', size: 255, required: true },
      { key: 'sector', type: 'string', size: 120, required: false },
      { key: 'region', type: 'string', size: 120, required: false },
      { key: 'askingPrice', type: 'float', required: false, min: 0 },
      { key: 'estimatedSynergy', type: 'float', required: false, min: 0 },
      { key: 'notes', type: 'string', size: 8192, required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['watchlist', 'shortlisted', 'due_diligence', 'rejected', 'acquired'],
        required: true,
        default: 'watchlist',
      },
      { key: 'createdAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'acquisition_targets_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'acquisition_targets_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      { key: 'acquisition_targets_createdAt_idx', type: 'key', attributes: ['createdAt'], orders: ['desc'] },
    ],
  },
  {
    collectionId: 'acquisition_models',
    name: 'Acquisition Models',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: true },
      { key: 'targetId', type: 'string', size: 255, required: true },
      { key: 'scenarioName', type: 'string', size: 255, required: true },
      { key: 'assumptions', type: 'json', required: true, size: 65535 },
      { key: 'projectedRevenue', type: 'float', required: true },
      { key: 'projectedCost', type: 'float', required: true },
      { key: 'projectedEbitdaProxy', type: 'float', required: true },
      { key: 'integrationRiskScore', type: 'float', required: true, min: 0, max: 1 },
      { key: 'generatedAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'acquisition_models_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'acquisition_models_targetId_idx', type: 'key', attributes: ['targetId'], orders: ['asc'] },
      { key: 'acquisition_models_generatedAt_idx', type: 'key', attributes: ['generatedAt'], orders: ['desc'] },
    ],
  },
  {
    collectionId: 'tender_models',
    name: 'Tender Models',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: true },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'targetMarginPct', type: 'float', required: true },
      { key: 'riskFactor', type: 'float', required: true },
      { key: 'effectiveCostRate', type: 'float', required: true },
      { key: 'recommendedHourlyRate', type: 'float', required: true },
      { key: 'assumptions', type: 'json', required: false, size: 65535 },
      { key: 'generatedAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'tender_models_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'tender_models_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'tender_models_generatedAt_idx', type: 'key', attributes: ['generatedAt'], orders: ['desc'] },
    ],
  },
  {
    collectionId: 'strategic_forecasts',
    name: 'Strategic Forecasts',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: true },
      { key: 'periodStart', type: 'datetime', required: true },
      { key: 'periodEnd', type: 'datetime', required: true },
      { key: 'horizonMonths', type: 'integer', required: true, min: 12, max: 36 },
      { key: 'forecastRevenue', type: 'float', required: true },
      { key: 'forecastCost', type: 'float', required: true },
      { key: 'forecastEbitdaProxy', type: 'float', required: true },
      { key: 'assumptions', type: 'json', required: false, size: 65535 },
      { key: 'generatedAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'strategic_forecasts_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'strategic_forecasts_periodStart_idx', type: 'key', attributes: ['periodStart'], orders: ['desc'] },
      { key: 'strategic_forecasts_generatedAt_idx', type: 'key', attributes: ['generatedAt'], orders: ['desc'] },
    ],
  },
  {
    collectionId: 'enterprise_risk_scores',
    name: 'Enterprise Risk Scores',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: true },
      { key: 'periodStart', type: 'datetime', required: true },
      { key: 'periodEnd', type: 'datetime', required: true },
      { key: 'riskScore', type: 'float', required: true, min: 0, max: 1 },
      { key: 'riskBand', type: 'enum', elements: ['low', 'medium', 'high', 'critical'], required: true },
      { key: 'drivers', type: 'json', required: false, size: 65535 },
      { key: 'generatedAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'enterprise_risk_scores_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'enterprise_risk_scores_riskBand_idx', type: 'key', attributes: ['riskBand'], orders: ['asc'] },
      { key: 'ers_genat_idx', type: 'key', attributes: ['generatedAt'], orders: ['desc'] },
    ],
  },
  {
    collectionId: 'security_events',
    name: 'Security Events',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: false },
      { key: 'actorId', type: 'string', size: 255, required: true },
      {
        key: 'eventType',
        type: 'enum',
        elements: [
          'privilege_change',
          'manager_scope_change',
          'entity_assignment_change',
          'break_glass_used',
          'suspicious_export_activity',
        ],
        required: true,
      },
      { key: 'severity', type: 'enum', elements: ['info', 'warning', 'critical'], required: true },
      { key: 'metadata', type: 'json', required: true, size: 65535 },
      { key: 'createdAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'security_events_eventType_idx', type: 'key', attributes: ['eventType'], orders: ['asc'] },
      { key: 'security_events_severity_idx', type: 'key', attributes: ['severity'], orders: ['asc'] },
      { key: 'security_events_createdAt_idx', type: 'key', attributes: ['createdAt'], orders: ['desc'] },
      { key: 'security_events_actorId_idx', type: 'key', attributes: ['actorId'], orders: ['asc'] },
      { key: 'security_events_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'cashflow_snapshots',
    name: 'Cashflow Snapshots',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: true },
      { key: 'periodStart', type: 'datetime', required: true },
      { key: 'periodEnd', type: 'datetime', required: true },
      { key: 'expectedReceipts', type: 'float', required: true },
      { key: 'expectedPayrollOutflow', type: 'float', required: true },
      { key: 'taxReserveEstimate', type: 'float', required: true },
      { key: 'netCashPosition', type: 'float', required: true },
      { key: 'assumptions', type: 'json', required: false, size: 65535 },
      { key: 'generatedAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'cashflow_snapshots_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'cashflow_snapshots_periodStart_idx', type: 'key', attributes: ['periodStart'], orders: ['desc'] },
      { key: 'cashflow_snapshots_generatedAt_idx', type: 'key', attributes: ['generatedAt'], orders: ['desc'] },
    ],
  },
  {
    collectionId: 'concentration_alerts',
    name: 'Concentration Alerts',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: true },
      { key: 'periodStart', type: 'datetime', required: true },
      { key: 'periodEnd', type: 'datetime', required: true },
      { key: 'topClients', type: 'json', required: true, size: 65535 },
      { key: 'concentrationPct', type: 'float', required: true },
      { key: 'thresholdPct', type: 'float', required: true },
      { key: 'severity', type: 'enum', elements: ['warning', 'critical'], required: true },
      { key: 'createdAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'concentration_alerts_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'concentration_alerts_createdAt_idx', type: 'key', attributes: ['createdAt'], orders: ['desc'] },
      { key: 'concentration_alerts_severity_idx', type: 'key', attributes: ['severity'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'margin_leakage_alerts',
    name: 'Margin Leakage Alerts',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: true },
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteId', type: 'string', size: 255, required: true },
      { key: 'shiftId', type: 'string', size: 255, required: false },
      {
        key: 'leakageType',
        type: 'enum',
        elements: [
          'worked_gt_scheduled',
          'excessive_breaks',
          'repeated_reject_resubmit',
          'approval_outside_scope',
          'manual_time_edits_spike',
        ],
        required: true,
      },
      { key: 'expectedValue', type: 'float', required: true },
      { key: 'actualValue', type: 'float', required: true },
      { key: 'severity', type: 'enum', elements: ['warning', 'critical'], required: true },
      { key: 'createdAt', type: 'datetime', required: true },
      { key: 'resolved', type: 'boolean', required: true, default: false },
      { key: 'resolvedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'margin_leakage_alerts_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'margin_leakage_alerts_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'margin_leakage_alerts_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      { key: 'mleak_type_idx', type: 'key', attributes: ['leakageType'], orders: ['asc'] },
      { key: 'margin_leakage_alerts_createdAt_idx', type: 'key', attributes: ['createdAt'], orders: ['desc'] },
      { key: 'margin_leakage_alerts_severity_idx', type: 'key', attributes: ['severity'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'contract_dependency_alerts',
    name: 'Contract Dependency Alerts',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: true },
      { key: 'periodStart', type: 'datetime', required: true },
      { key: 'periodEnd', type: 'datetime', required: true },
      { key: 'expiringWithinDays', type: 'integer', required: true, min: 1, max: 3650 },
      { key: 'revenueAtRisk', type: 'float', required: true },
      { key: 'percentRevenueAtRisk', type: 'float', required: true },
      { key: 'thresholdPct', type: 'float', required: true },
      { key: 'severity', type: 'enum', elements: ['warning', 'critical'], required: true },
      { key: 'createdAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'cdep_entity_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'cdep_created_idx', type: 'key', attributes: ['createdAt'], orders: ['desc'] },
      { key: 'cdep_severity_idx', type: 'key', attributes: ['severity'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'resilience_snapshots',
    name: 'Resilience Snapshots',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: true },
      { key: 'periodStart', type: 'datetime', required: true },
      { key: 'periodEnd', type: 'datetime', required: true },
      { key: 'staffDepthScore', type: 'float', required: true },
      { key: 'payeBalanceScore', type: 'float', required: true },
      { key: 'complianceHealthScore', type: 'float', required: true },
      { key: 'incidentStabilityScore', type: 'float', required: true },
      { key: 'coverageConsistencyScore', type: 'float', required: true },
      { key: 'compositeResilienceScore', type: 'float', required: true },
      { key: 'generatedAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'resilience_snapshots_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'resilience_snapshots_periodStart_idx', type: 'key', attributes: ['periodStart'], orders: ['desc'] },
      { key: 'resilience_snapshots_generatedAt_idx', type: 'key', attributes: ['generatedAt'], orders: ['desc'] },
    ],
  },
  {
    collectionId: 'tender_win_models',
    name: 'Tender Win Models',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: true },
      { key: 'region', type: 'string', size: 120, required: true },
      { key: 'sector', type: 'string', size: 120, required: true },
      { key: 'proposedRate', type: 'float', required: true },
      { key: 'competitivenessScore', type: 'float', required: true, min: 0, max: 1 },
      { key: 'experienceScore', type: 'float', required: true, min: 0, max: 1 },
      { key: 'riskPremiumScore', type: 'float', required: true, min: 0, max: 1 },
      { key: 'predictedWinProbability', type: 'float', required: true, min: 0, max: 1 },
      { key: 'generatedAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'tender_win_models_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'tender_win_models_generatedAt_idx', type: 'key', attributes: ['generatedAt'], orders: ['desc'] },
      { key: 'tender_win_models_region_idx', type: 'key', attributes: ['region'], orders: ['asc'] },
      { key: 'tender_win_models_sector_idx', type: 'key', attributes: ['sector'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'employment_risk_flags',
    name: 'Employment Risk Flags',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'entityId', type: 'string', size: 255, required: true },
      { key: 'guardId', type: 'string', size: 255, required: true },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'siteId', type: 'string', size: 255, required: false },
      {
        key: 'riskType',
        type: 'enum',
        elements: ['high_client_dependency', 'long_term_same_site', 'high_hours_single_client'],
        required: true,
      },
      { key: 'metricValue', type: 'float', required: true },
      { key: 'thresholdValue', type: 'float', required: true },
      { key: 'severity', type: 'enum', elements: ['warning', 'critical'], required: true },
      { key: 'createdAt', type: 'datetime', required: true },
      { key: 'resolved', type: 'boolean', required: true, default: false },
      { key: 'resolvedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'employment_risk_flags_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'employment_risk_flags_guardId_idx', type: 'key', attributes: ['guardId'], orders: ['asc'] },
      { key: 'employment_risk_flags_riskType_idx', type: 'key', attributes: ['riskType'], orders: ['asc'] },
      { key: 'employment_risk_flags_createdAt_idx', type: 'key', attributes: ['createdAt'], orders: ['desc'] },
      { key: 'employment_risk_flags_severity_idx', type: 'key', attributes: ['severity'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'notification_outbox',
    name: 'Notification Outbox',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      {
        key: 'eventType',
        type: 'enum',
        elements: [
          'inviteSent',
          'shiftAssigned',
          'applicationApproved',
          'applicationRejected',
          'complianceSubmitted',
          'complianceApproved',
          'complianceRejected',
          'timesheetSubmitted',
          'timesheetApproved',
          'timesheetRejected',
          'incidentInterim',
          'incidentFinal',
          'complianceExpiryWarning',
          'complianceEscalation',
          'marginAlertCreated',
          'securityEventCreated',
        ],
        required: true,
      },
      { key: 'toEmail', type: 'email', required: true },
      { key: 'subject', type: 'string', size: 255, required: true },
      { key: 'payload', type: 'json', required: true, size: 65535 },
      {
        key: 'status',
        type: 'enum',
        elements: ['pending', 'sent', 'failed'],
        required: true,
        default: 'pending',
      },
      { key: 'attempts', type: 'integer', required: true, default: 0, min: 0, max: 99 },
      { key: 'lastError', type: 'string', size: 2048, required: false },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'userId', type: 'string', size: 255, required: false },
      { key: 'createdAt', type: 'datetime', required: true },
      { key: 'updatedAt', type: 'datetime', required: false },
    ],
    indexes: [
      { key: 'notification_outbox_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      { key: 'notification_outbox_eventType_idx', type: 'key', attributes: ['eventType'], orders: ['asc'] },
      { key: 'notification_outbox_createdAt_idx', type: 'key', attributes: ['createdAt'], orders: ['desc'] },
      { key: 'notification_outbox_userId_idx', type: 'key', attributes: ['userId'], orders: ['asc'] },
      {
        key: 'nout_status_event_cr_idx',
        type: 'key',
        attributes: ['status', 'eventType', 'createdAt'],
        orders: ['asc', 'asc', 'desc'],
      },
    ],
  },
  {
    collectionId: 'margin_alerts',
    name: 'Margin Alerts',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteId', type: 'string', size: 255, required: true },
      { key: 'shiftId', type: 'string', size: 255, required: false },
      { key: 'periodStart', type: 'datetime', required: true },
      { key: 'periodEnd', type: 'datetime', required: true },
      {
        key: 'alertType',
        type: 'enum',
        elements: [
          'low_margin',
          'negative_margin',
          'overtime_spike',
          'under_coverage',
          'staffing_shortage',
          'contract_risk',
          'enterprise_risk',
        ],
        required: true,
      },
      { key: 'thresholdValue', type: 'float', required: true },
      { key: 'actualValue', type: 'float', required: true },
      {
        key: 'severity',
        type: 'enum',
        elements: ['warning', 'critical'],
        required: true,
      },
      { key: 'resolved', type: 'boolean', required: true, default: false },
      { key: 'resolvedAt', type: 'datetime', required: false },
      { key: 'createdAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'margin_alerts_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'margin_alerts_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      { key: 'margin_alerts_alertType_idx', type: 'key', attributes: ['alertType'], orders: ['asc'] },
      { key: 'margin_alerts_severity_idx', type: 'key', attributes: ['severity'], orders: ['asc'] },
      { key: 'margin_alerts_createdAt_idx', type: 'key', attributes: ['createdAt'], orders: ['desc'] },
    ],
  },
  {
    collectionId: 'forecast_models',
    name: 'Forecast Models',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteId', type: 'string', size: 255, required: false },
      { key: 'modelType', type: 'enum', elements: ['rolling_average'], required: true, default: 'rolling_average' },
      { key: 'lookbackDays', type: 'integer', required: true, min: 7, max: 365, default: 28 },
      { key: 'parameters', type: 'json', required: false, size: 65535 },
      { key: 'active', type: 'boolean', required: true, default: true },
      { key: 'createdAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'forecast_models_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'forecast_models_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      { key: 'forecast_models_modelType_idx', type: 'key', attributes: ['modelType'], orders: ['asc'] },
      { key: 'forecast_models_active_idx', type: 'key', attributes: ['active'], orders: ['asc'] },
    ],
  },
  {
    collectionId: 'forecast_snapshots',
    name: 'Forecast Snapshots',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteId', type: 'string', size: 255, required: true },
      { key: 'periodStart', type: 'datetime', required: true },
      { key: 'periodEnd', type: 'datetime', required: true },
      { key: 'predictedHours', type: 'float', required: true },
      { key: 'predictedRevenue', type: 'float', required: true },
      { key: 'predictedCost', type: 'float', required: true },
      { key: 'generatedAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'forecast_snapshots_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'forecast_snapshots_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      { key: 'forecast_snapshots_periodStart_idx', type: 'key', attributes: ['periodStart'], orders: ['desc'] },
      { key: 'forecast_snapshots_generatedAt_idx', type: 'key', attributes: ['generatedAt'], orders: ['desc'] },
    ],
  },
  {
    collectionId: 'demand_predictions',
    name: 'Demand Predictions',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteId', type: 'string', size: 255, required: true },
      { key: 'date', type: 'datetime', required: true },
      { key: 'predictedRequiredGuards', type: 'float', required: true },
      { key: 'predictedAvailableGuards', type: 'float', required: true },
      { key: 'shortageRiskScore', type: 'float', required: true },
      { key: 'generatedAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'demand_predictions_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'demand_predictions_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      { key: 'demand_predictions_date_idx', type: 'key', attributes: ['date'], orders: ['desc'] },
      { key: 'demand_predictions_generatedAt_idx', type: 'key', attributes: ['generatedAt'], orders: ['desc'] },
    ],
  },
  {
    collectionId: 'contract_health_snapshots',
    name: 'Contract Health Snapshots',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'contractId', type: 'string', size: 255, required: true },
      { key: 'marginTrend', type: 'float', required: true },
      { key: 'slaComplianceScore', type: 'float', required: true },
      { key: 'incidentRate', type: 'float', required: true },
      { key: 'revenueTrend', type: 'float', required: true },
      { key: 'riskScore', type: 'float', required: true },
      { key: 'generatedAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'chs_contract_idx', type: 'key', attributes: ['contractId'], orders: ['asc'] },
      { key: 'chs_generated_idx', type: 'key', attributes: ['generatedAt'], orders: ['desc'] },
      { key: 'chs_risk_idx', type: 'key', attributes: ['riskScore'], orders: ['desc'] },
    ],
  },
  {
    collectionId: 'finance_events',
    name: 'Finance Events',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      {
        key: 'eventType',
        type: 'enum',
        elements: ['payroll_export_ready', 'invoice_export_ready', 'rate_change_approved'],
        required: true,
      },
      { key: 'referenceId', type: 'string', size: 255, required: true },
      { key: 'entityId', type: 'string', size: 255, required: false },
      { key: 'clientId', type: 'string', size: 255, required: false },
      { key: 'provider', type: 'enum', elements: ['xero', 'quickbooks'], required: true },
      { key: 'status', type: 'enum', elements: ['pending', 'sent', 'acknowledged', 'failed'], required: true, default: 'pending' },
      { key: 'payloadHash', type: 'string', size: 128, required: true },
      { key: 'createdAt', type: 'datetime', required: true },
    ],
    indexes: [
      { key: 'finance_events_entityId_idx', type: 'key', attributes: ['entityId'], orders: ['asc'] },
      { key: 'finance_events_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'finance_events_eventType_idx', type: 'key', attributes: ['eventType'], orders: ['asc'] },
      { key: 'finance_events_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      { key: 'finance_events_createdAt_idx', type: 'key', attributes: ['createdAt'], orders: ['desc'] },
    ],
  },
  {
    collectionId: 'applications',
    name: 'Applications',
    documentSecurity: true,
    enabled: true,
    permissions: AUTHENTICATED_RW,
    attributes: [
      { key: 'guardId', type: 'string', size: 255, required: true },
      { key: 'guardName', type: 'string', size: 255, required: true },
      { key: 'shiftId', type: 'string', size: 255, required: true },
      { key: 'clientId', type: 'string', size: 255, required: true },
      { key: 'siteId', type: 'string', size: 255, required: true },
      { key: 'shiftDetails', type: 'json', required: true, size: 65535 },
      { key: 'eligibilityScore', type: 'json', required: true, size: 65535 },
      { key: 'message', type: 'string', size: 2000, required: false },
      {
        key: 'status',
        type: 'enum',
        elements: ['pending', 'approved', 'rejected', 'withdrawn', 'expired'],
        required: true,
        default: 'pending',
      },
      { key: 'appliedAt', type: 'datetime', required: true },
      { key: 'reviewedAt', type: 'datetime', required: false },
      { key: 'reviewedBy', type: 'string', size: 255, required: false },
      { key: 'reviewerName', type: 'string', size: 255, required: false },
      { key: 'reviewNotes', type: 'string', size: 4096, required: false },
      { key: 'rejectionReason', type: 'string', size: 255, required: false },
      { key: 'withdrawnAt', type: 'datetime', required: false },
      { key: 'withdrawalReason', type: 'string', size: 1024, required: false },
    ],
    indexes: [
      { key: 'applications_guardId_idx', type: 'key', attributes: ['guardId'], orders: ['asc'] },
      { key: 'applications_shiftId_idx', type: 'key', attributes: ['shiftId'], orders: ['asc'] },
      { key: 'applications_clientId_idx', type: 'key', attributes: ['clientId'], orders: ['asc'] },
      { key: 'applications_siteId_idx', type: 'key', attributes: ['siteId'], orders: ['asc'] },
      { key: 'applications_status_idx', type: 'key', attributes: ['status'], orders: ['asc'] },
      {
        key: 'applications_appliedAt_idx',
        type: 'key',
        attributes: ['appliedAt'],
        orders: ['desc'],
      },
      {
        key: 'apps_shift_guard_stat_ap_idx',
        type: 'key',
        attributes: ['shiftId', 'guardId', 'status', 'appliedAt'],
        orders: ['asc', 'asc', 'asc', 'desc'],
      },
    ],
  },
];

export const COLLECTION_BY_ID = new Map(
  COLLECTION_DEFINITIONS.map((collection) => [collection.collectionId, collection])
);
